stages:
  - test

runtest:
  image: ${TESTING_DOCKER_IMAGE}
  stage: test
  script:
    - cd asgn${TESTING_LAB}
    - git clone https://oauth2:${TESTING_SECRET}@git.ucsc.edu/cse13s_master/cse13s_resources.git
    - cp ./cse13s_resources/Assignments/asgn${TESTING_LAB}/test_asgn${TESTING_LAB}.py .
    - python3 test_asgn${TESTING_LAB}.py
    - /bin/rm -r cse13s_resources/ 
    - /bin/rm -f test_asgn${TESTING_LAB}.py

